development:
  secret_key_base: 42xxx35
  dynamodb_access_key_id: <%= ENV["AKIA2ODTBXIKAZ7ZCOTP"] %>
  dynamodb_secret_access_key: <%= ENV["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"] %>
  region: <%= ENV["us-west-2"] %>


#test:
#  secret_key_base: 9dfcxxx5e
#  dynamodb_access_key_id: <%#= ENV["DYNAMODB_ACCESS_KEY_ID"] %>
#  dynamodb_secret_access_key: <%#= ENV["DYNAMODB_SECRET_ACCESS_KEY_ID"] %>
#  region: <%#= ENV["DYNAMODB_REGION"] %>

#production:
#  secret_key_base: <%#= ENV["SECRET_KEY_BASE"] %>
#  dynamodb_access_key_id: <%#= ENV["DYNAMODB_ACCESS_KEY_ID"] %>
#  dynamodb_secret_access_key: <%#= ENV["DYNAMODB_SECRET_ACCESS_KEY_ID"] %>
#  region: <%#= ENV["DYNAMODB_REGION"] %>